<br>
<br>
<br>

<p align="right">
```{r share, echo = FALSE, warning = FALSE, message = FALSE, fig.align='center', results = "asis"}
# sorteia participante para relatar no texto
library(fontawesome)

cat("[")
fa("twitter-square", margin_left = "0.2em", margin_right = "0.2em", height = "2em", width = "2em")
cat("](https://twitter.com/share?url=rehab-tech.github.io/proteses/)")
cat("&nbsp;&nbsp;&nbsp;")
cat("[")
fa("facebook-square", margin_left = "0.2em", margin_right = "0.2em", height = "2em", width = "2em")
cat("](http://www.facebook.com/sharer.php?u=rehab-tech.github.io/proteses/)")
cat("&nbsp;&nbsp;&nbsp;")
cat("[")
fa("linkedin", margin_left = "0.2em", margin_right = "0.2em", height = "2em", width = "2em")
cat("](http://www.linkedin.com/shareArticle?mini=true&amp;url=rehab-tech.github.io/proteses/)")
```
</p>

<!--script for generating HORIZONTAL LINE-->
<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">

# **12.	Busca e Seleção das Intervenções para Protetização de Membros Inferiores**

<br>

Foram incluídos artigos com dados primários (estudos de caso, ensaios clínicos) e secundários (revisões sistemáticas, diretrizes) disponíveis na integra, redigidos em inglês ou em português, que descrevam intervenções fisioterapêuticas para as fases de pré e/ou pós-protetização em PcAMI, selecionaram-se artigos sem limite de data inicial e publicados até 15/08/2020.

<br>

A busca dos estudos foi realizada na base de dados Physiotherapy Evidence Data base Scale (PEDro) (https://www.pedro.org.au), selecionada por apresentarem produções científicas, vinculadas à Grande Área Ciências da Saúde e Subárea Fisioterapia e Terapia Ocupacional. A PEDro é produzida pelo Institute for Musculoskeletal Health da School of Public Health da University of Sydney e é hospedado pela Neuroscience Research Australia (NeuRA). Estudos com dados secundários tiveram suas listas de referências inspecionadas para inclusão de estudos não encontrados na busca original ou exclusão de duplicatas.

<br>

Foram utilizados os seguintes descritores em português e em inglês: Amputação (Amputation); Fisioterapia (Physiotherapy); Reabilitação (Rehabilitation); Prótese (Prosthetics); Membros Inferiores (LowerLimb). Além disso, utilizou-se operador lógico booleano “AND” e “OR”, para relacionar as palavras-chave. As buscas dos estudos foram realizadas em 26/08/2020 com a seguinte expressão de busca: “amputation*"lowerlimb"*physiotherapy*rehabilitation*prosthesis”.

<br>
