---
title: Reabilitação de Pessoas com Amputação
---
<br>
<br>
<br>

<p align="right">
```{r share, echo = FALSE, warning = FALSE, message = FALSE, fig.align='center', results = "asis"}
# sorteia participante para relatar no texto
library(fontawesome)

cat("[")
fa("twitter-square", margin_left = "0.2em", margin_right = "0.2em", height = "2em", width = "2em")
cat("](https://twitter.com/share?url=rehab-tech.github.io/proteses/)")
cat("&nbsp;&nbsp;&nbsp;")
cat("[")
fa("facebook-square", margin_left = "0.2em", margin_right = "0.2em", height = "2em", width = "2em")
cat("](http://www.facebook.com/sharer.php?u=rehab-tech.github.io/proteses/)")
cat("&nbsp;&nbsp;&nbsp;")
cat("[")
fa("linkedin", margin_left = "0.2em", margin_right = "0.2em", height = "2em", width = "2em")
cat("](http://www.linkedin.com/shareArticle?mini=true&amp;url=rehab-tech.github.io/proteses/)")
```
</p>

<!--script for generating HORIZONTAL LINE-->
<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">

## **Apresentação**  

<br>

A amputação de membros inferiores pode resultar em sequelas físicas, psicológicas e sociais, constituindo um problema de saúde pública no Brasil e no mundo. O impacto econômico da deficiência chama a atenção: a previdência social gasta milhões de reais com aposentadorias por invalidez, sendo estimado que as amputações do membro inferior correspondam a aproximadamente 85% de todas as amputações de membros.  

<br>

Com as alterações biopsicossociais associadas à amputação de membros, a prótese tem um papel chave na reparação física e psicológica destes indivíduos, no entanto, reabilitar não significa adquirir uma prótese. Faz-se necessário um programa de reabilitação que permita ao paciente adaptar-se ao seu ambiente, favorecer sua recuperação funcional, psicológica e social, promover assim sua integração familiar e profissional.  

<br>

Frente a essa complexidade, entra em cena o fisioterapeuta, cabendo aqui destacar a necessidade do conhecimento técnico-científico atualizado e baseado em evidências para o manejo da pessoa com amputação. Este manual surge então pela necessidade de reunir e sistematizar propostas de reabilitação para essa população. Este manual foi criado como produto técnico da dissertação de mestrado de Caroline Lacerda Alves de Oliveira, do Programa de Pós-Graduação Stricto Sensu em Desenvolvimento Local do Centro Universitário Augusto Motta, UNISUAM/RJ, turma fora de sede, sob a orientação do Dr. Arthur de Sá Ferreira.  

<br>

Este manual instrutivo tem por objetivo nortear os fisioterapeutas nas etapas do processo de reabilitação de pessoas com amputação de membros inferiores. Olhar a pessoa com amputação em seu contexto biopsicossocial amplia os horizontes e contextualiza o indivíduo, a família, a comunidade para um processo de reabilitação mais efetivo. Aqui foram incluídas orientações para fisioterapeutas no processo de reabilitação das pessoas com amputação de membro inferior nas etapas de pré e pós-protetização.  

<br>

Este Manual Instrutivo foi construído com o intuito de fornecer informações a ajudar os fisioterapeutas na tomada de decisões para traçar um projeto terapêutico para as pessoas com amputação de membro inferior (PcAMI), levando a melhores resultados clínicos. Não pretende definir um padrão de atendimento e não deve ser interpretado como um, até porque variações na prática ocorrerão inevitavelmente quando se levam em consideração as necessidades individuais de cada pessoa, recursos disponíveis e a experiência clínica de cada profissional.  

<br>

O fisioterapeuta que utilizar este manual é responsável pela avaliação e adequação das técnicas propostas, modificando-as quando necessário em virtude das diferentes situações clínicas apresentadas pelos pacientes. O presente Manual foi desenvolvido após a realização de uma revisão sistematizada de obras publicadas por autores sobre esse assunto no mundo, tendo o papel de resumir, de examinar a natureza da atividade de pesquisa e de encontrar lacunas até o ano de 2020.  
